name: portfolio-dev

on:
  push: 
    branches: [ develop ]

jobs:
  build: 
    runs-on: [self-hosted, linux, x64, dev, front]
  
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm i
        cd 02-front
        npm i
        npm run build:test
    - name: PM2 restart
      run: |
        pm2 stop portfolio-dev-front
        pm2 start npm --name portfolio-dev-front -- run start:test
        pm2 save --force
