name: portfolio-prod

on:
  push: 
    branches: [ main ]

jobs:
  build: 
    runs-on: [self-hosted, linux, x64, prod, front]
  
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm i
        cd 02-front
        npm i
        npm run build